baseURL = 'https://blog.thibaud.io/'
languageCode = 'en-US'
title = "rheneross"
theme = "hugo-bearcub"
defaultContentLanguage = "en"

enableRobotsTXT = true

[languages]
[languages.en]
title = "rheneross"
languageName = "English"
LanguageCode = "en-US"
contentDir = "content"
[languages.en.params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
# The description of your website
description = "Thibaud's blog"

# The path to your favicon
favicon = "images/favicon.png"

# This title is used as the site_name on the Hugo's internal opengraph
# structured data template
title = "rheneross"

# Dates are displayed following the format below. For more information about
# formatting, see https://gohugo.io/functions/format/
dateFormat = "2006-01-02"

# If your blog is multilingual but you haven't translated a page, this theme
# will create a disabled link. By setting `hideUntranslated` to true, you can
# have the theme simply not show any link
hideUntranslated = false

# (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
# "herman". The former is what you see on Bear Cub's demo (an optimized
# version of Hugo Bear Blog), while the latter has a more modern look based on
# Herman Martinus's version of the Blogster Minimal theme for Astro.
themeStyle = "original"

# (EXPERIMENTAL) This theme is capable of dynamically generating social cards
# for posts that don't have `images` defined in their front matter; By setting
# `generateSocialCard` to false, you can prevent this behavior. For more
# information see layouts/partials/social_card.html
generateSocialCard = true

bluesky = "https://bsky.app/profile/rheneross.bsky.social"

# Author metadata. This is mostly used for the RSS feed of your site, but the
# email is also added to the footer of each post. You can hide the "reply to"
# link by using a `hideReply` param in front matter.
[params.author]
name = "Thibaud" # Your name as shown in the RSS feed metadata
